# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

flutter_application_path = '../multi_engine'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'MultiFlutterEngineApp' do
  # use_frameworks!
  install_all_flutter_pods(flutter_application_path)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
